---
---
# ***Veri Analizi***
---
---

# **Numpy**
Numerical Python

## **Numpy Kütüphanesini Dahil etme**

In [4]:
import numpy as np

## **Numpy Dizisi Oluşturma**

In [ ]:
liste=[6,4,2]
print(type(liste))

npArray=np.array(liste)
print(type(npArray))

<class 'list'>
<class 'numpy.ndarray'>


### **np.arange()**

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

### **np.zeros()**

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

### **np.ones()**

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

### **np.empty()**

In [ ]:
np.empty(4)

array([1., 1., 1., 1.])

### **np.linspace()**

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## **Neden Numpy?**

In [2]:
d1=[1,2,3]
d2=[4,5,6]
# print(d1*d2)

In [ ]:
d1=np.array(d1)
d2=np.array(d2)
print(d1*d2)

[ 4 10 18]


## **Veri eklemek**

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.append(arr,9)

array([2, 1, 5, 3, 7, 4, 6, 8, 9])

In [ ]:
np.insert(arr,0,11)

array([11,  2,  1,  5,  3,  7,  4,  6,  8])

## **Veri silmek**

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.delete(arr,2)

array([2, 1, 3, 7, 4, 6, 8])

In [ ]:
np.delete(arr,np.where(arr==3))

array([2, 1, 5, 7, 4, 6, 8])

## **Sıralama**

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## **Birleştirme**

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

## **Matrisler**

In [ ]:
x = np.array([[2, 1],
              [5, 3]])
np.sort(x)

array([[1, 2],
       [3, 5]])

In [ ]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### **np.vstack() / np.hstack()**

In [ ]:
x = np.array([[1, 2],
              [3, 4]])
np.hstack((x,[[8, 9],
              [10,11]]))

array([[ 1,  2,  8,  9],
       [ 3,  4, 10, 11]])

In [ ]:
np.vstack((x,[[8, 9],
              [10,11]]))

array([[ 1,  2],
       [ 3,  4],
       [ 8,  9],
       [10, 11]])

### **np.hsplit() / np.vsplit()**

In [ ]:
arr=np.array([[1,  2,  3, 4,  5,  6],
              [7,  8,  9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(arr,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]), array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [ ]:
np.vsplit(arr,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

## **Boyut işlemleri**

In [ ]:
arr=np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [0, 1, 2, 3],
              [4, 5, 6, 7],
              [0 ,1 ,2, 3],
              [4, 5, 6, 7]])

### **Boyut sayısı**

In [ ]:
arr.ndim

2

### **Eleman sayısı**

In [ ]:
arr.size

24

### **Boyut bilgisi**

In [ ]:
arr.shape

(6, 4)

### **Yeniden boyutlandırma**

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(a.shape)
a=a.reshape(-1,6)
print(a.shape)

(6,)
(1, 6)


## **Karakterlere erişmek**

In [ ]:
data = np.array([1, 2, 3])
data[1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr[1]

array([5, 6, 7, 8])

In [ ]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
arr[arr<6]

array([1, 2, 3, 4, 5])

## **Operatörler**

In [ ]:
a = np.array([1, 2])
b = np.array([2, 3])

### **Toplama**

In [ ]:
a + b

array([3, 5])

In [ ]:
a + 1

array([2, 3])

### **Çıkarma**

In [ ]:
b - a

array([1, 1])

In [ ]:
a - 1

array([0, 1])

### **Çarpma**

In [ ]:
a * b

array([2, 6])

In [ ]:
a * 3

array([3, 6])

In [11]:
m = np.array([[1,2,3],
             [4,5,6]])
n = np.array([[7,8,13,1],
             [9,10,14,2],
              [11,12,15,3]])

# m * n
# m @ n
# m.dot(n)

array([[ 58,  64,  86,  14],
       [139, 154, 212,  32]])

### **Bölme**

In [ ]:
b / a

array([2. , 1.5])

In [ ]:
b / 2

array([1. , 1.5])

In [13]:
# m / n

## **Elzem Fonksiyonlar**

In [ ]:
data=np.arange(2,20,3)
data

array([ 2,  5,  8, 11, 14, 17])

#### **sum()**

In [ ]:
data.sum()

57

### **max()**

In [ ]:
data.max()

17

### **min()**

In [ ]:
data.min()

2

### **mean()**

In [ ]:
data.mean()

9.5

### **np.median()**

In [ ]:
np.median(data)

9.5

### **Transpose**

In [14]:
arr=np.array([[1,2,3],
             [4,5,6]])
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

###**np.flip()**

In [15]:
np.flip(arr)

array([[6, 5, 4],
       [3, 2, 1]])

### **reshape()**

In [17]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### **flatten()**

In [18]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

### **ravel()**

In [19]:
arr.ravel() # ana diziye bağlıdır

array([1, 2, 3, 4, 5, 6])

# **Pandas**

## **Pandas kütüphanesini dahil etme**

In [20]:
import pandas as pd
import numpy as np

## **Pandas Series oluşturma**

In [21]:
seri=pd.Series([1,2,3,4,5,np.nan])
seri

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64

## **Pandas DataFrame oluşturma**

In [ ]:
data=pd.DataFrame({"sehirler":["malatya","yozgat","istanbul"],
                   "plakalar":[44,66,34],
                   "ilceler":["battalgazi","sorgun","esenyurt"]})
data

sehirler  plakalar     ilceler
0   malatya        44  battalgazi
1    yozgat        66      sorgun
2  istanbul        34    esenyurt

## **Veriye İlk Temas!**

### **Veriyi içe aktarmak**

In [22]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [23]:
data=pd.read_csv(r"/content/gdrive/MyDrive/Colab Notebooks/Churn_Modelling.csv")

### **Verileri görüntüleme**

In [26]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
data.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0

### **Verinin kopyasını oluşturmak**

In [27]:
df=data.copy()

### **Index ve Sütun isimlerine erişmek**

In [28]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [29]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

### **Seçim işlemleri**

In [30]:
df[:3]

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [31]:
df["Balance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...    
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [32]:
type(df.Balance)

pandas.core.series.Series

In [33]:
df[["Balance","Age"]].head()

Balance  Age
0       0.00   42
1   83807.86   41
2  159660.80   42
3       0.00   39
4  125510.82   43

In [34]:
print(df["Surname"][2])

Onio


In [35]:
print(df["Surname"][0:5])


0    Hargrave
1        Hill
2        Onio
3        Boni
4    Mitchell
Name: Surname, dtype: object


#### **loc (değişkenler ile seçim işlemleri)**

In [36]:
df.loc[2:5, "Surname":"Balance"]

Surname  CreditScore Geography  Gender  Age  Tenure    Balance
2      Onio          502    France  Female   42       8  159660.80
3      Boni          699    France  Female   39       1       0.00
4  Mitchell          850     Spain  Female   43       2  125510.82
5       Chu          645     Spain    Male   44       8  113755.78

In [ ]:
df.loc[:8, ["Age", "Tenure", "Exited"]]

Age  Tenure  Exited
0   42       2       1
1   41       1       0
2   42       8       1
3   39       1       0
4   43       2       0
5   44       8       1
6   50       7       0
7   29       4       1
8   44       4       0

#### **iloc (indexler ile seçim işlemleri)**

In [ ]:
df.iloc[2:5, 3:7]

CreditScore Geography  Gender  Age
2          502    France  Female   42
3          699    France  Female   39
4          850     Spain  Female   43

In [ ]:
df.iloc[[2,3,4,5],[7,8,9]]

Tenure    Balance  NumOfProducts
2       8  159660.80              3
3       1       0.00              2
4       2  125510.82              1
5       8  113755.78              2

#### **Boolean Indexleme**

In [ ]:
df["Balance"]>10000

0       False
1        True
2        True
3       False
4        True
        ...  
9995    False
9996     True
9997    False
9998     True
9999     True
Name: Balance, Length: 10000, dtype: bool

In [ ]:
df[df["Balance"]>220000]

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
2092       2093    15757408        Lo          655     Spain    Male   38   
3280       3281    15715622    To Rot          583    France  Female   57   
3588       3589    15571958  McIntosh          489     Spain    Male   40   
8733       8734    15714241    Haddon          749     Spain    Male   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
2092       3  250898.09              3          0               1   
3280       3  238387.56              1          0               1   
3588       3  221532.80              1          1               0   
8733       9  222267.63              1          0               0   

      EstimatedSalary  Exited  
2092         81054.00       1  
3280        147964.99       1  
3588        171867.08       0  
8733        101108.85       1

### **Gözlem birimi silme**

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.drop(2, axis=0).head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df.drop(2, axis=0,inplace=True)
df.reset_index().head()

index  RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0      0          1    15634602  Hargrave          619    France  Female   42   
1      1          2    15647311      Hill          608     Spain  Female   41   
2      3          4    15701354      Boni          699    France  Female   39   
3      4          5    15737888  Mitchell          850     Spain  Female   43   
4      5          6    15574012       Chu          645     Spain    Male   44   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       1       0.00              2          0               0   
3       2  125510.82              1          1               1   
4       8  113755.78              2          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2         93826.63       0  
3         79084.10       0  
4        149756.71       1

### **Değişken silme**

In [ ]:
df.drop("RowNumber",axis=1,inplace=True)
df.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15634602  Hargrave          619    France  Female   42       2   
1    15647311      Hill          608     Spain  Female   41       1   
3    15701354      Boni          699    France  Female   39       1   
4    15737888  Mitchell          850     Spain  Female   43       2   
5    15574012       Chu          645     Spain    Male   44       8   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   
5  113755.78              2          1               0        149756.71   

   Exited  
0       1  
1       0  
3       0  
4       0  
5       1

In [ ]:
df.drop(["Surname","Gender","Age"],axis=1).head()

CustomerId  CreditScore Geography  Tenure    Balance  NumOfProducts  \
0    15634602          619    France       2       0.00              1   
1    15647311          608     Spain       1   83807.86              1   
3    15701354          699    France       1       0.00              2   
4    15737888          850     Spain       2  125510.82              1   
5    15574012          645     Spain       8  113755.78              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
3          0               0         93826.63       0  
4          1               1         79084.10       0  
5          1               0        149756.71       1

### **Değer değiştirmek**

In [ ]:
df["Geography"][0]="Spain"
df.head()

<ipython-input-207-63aca10d8e27>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Geography"][0]="Spain"


CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15634602  Hargrave          619     Spain  Female   42       2   
1    15647311      Hill          608     Spain  Female   41       1   
3    15701354      Boni          699    France  Female   39       1   
4    15737888  Mitchell          850     Spain  Female   43       2   
5    15574012       Chu          645     Spain    Male   44       8   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   
5  113755.78              2          1               0        149756.71   

   Exited  
0       1  
1       0  
3       0  
4       0  
5       1

### **Describe fonksiyonu**

In [ ]:
df.describe()

CustomerId  CreditScore          Age       Tenure        Balance  \
count  9.999000e+03  9999.000000  9999.000000  9999.000000    9999.000000   
mean   1.569095e+07   650.543654    38.921492     5.012501   76477.570965   
std    7.193622e+04    96.646716    10.488286     2.892165   62394.980434   
min    1.556570e+07   350.000000    18.000000     0.000000       0.000000   
25%    1.562854e+07   584.000000    32.000000     3.000000       0.000000   
50%    1.569074e+07   652.000000    37.000000     5.000000   97188.620000   
75%    1.575324e+07   718.000000    44.000000     7.000000  127640.395000   
max    1.581569e+07   850.000000    92.000000    10.000000  250898.090000   

       NumOfProducts    HasCrCard  IsActiveMember  EstimatedSalary      Exited  
count    9999.000000  9999.000000     9999.000000      9999.000000  9999.00000  
mean        1.530053     0.705471        0.515152    100088.855610     0.20362  
std         0.581498     0.455854        0.499795     57513.202241     0.40271  
min         1.000000     0.000000        0.000000        11.580000     0.00000  
25%         1.000000     0.000000        0.000000     50992.930000     0.00000  
50%         1.000000     1.000000        1.000000    100187.430000     0.00000  
75%         2.000000     1.000000        1.000000    149392.065000     0.00000  
max         4.000000     1.000000        1.000000    199992.480000     1.00000

In [ ]:
df["Age"].mean()

38.92149214921492

### **Aggregation (toplulaştırma) ve Groupby (gruplama) işlemleri**

In [ ]:
df.groupby("Gender")["Age"].mean()

Gender
Female    39.237781
Male      38.658237
Name: Age, dtype: float64

In [ ]:
df.groupby("Gender").agg({"Age": "mean"})

Age
Gender           
Female  39.237781
Male    38.658237

In [ ]:
df.groupby("Gender").agg({"Age": ["mean", "sum"]})

Age        
             mean     sum
Gender                   
Female  39.237781  178218
Male    38.658237  210958

In [ ]:
df.groupby(["Gender","Geography"])["Age","Balance"].mean()

<ipython-input-213-429e54c9df38>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(["Gender","Geography"])["Age","Balance"].mean()


Age        Balance
Gender Geography                          
Female France     38.771138   60305.399039
       Germany    40.154233  119145.966471
       Spain      39.201835   59807.173183
Male   France     38.296404   63546.284875
       Germany    39.424772  120259.668222
       Spain      38.649135   63352.833746

In [ ]:
df.groupby(["Gender","Geography"]).agg({"Age": "mean",
                                        "Balance":["mean","std"]})

Age        Balance              
                       mean           mean           std
Gender Geography                                        
Female France     38.771138   60305.399039  63557.654857
       Germany    40.154233  119145.966471  26340.359839
       Spain      39.201835   59807.173183  64277.027904
Male   France     38.296404   63546.284875  64562.683717
       Germany    39.424772  120259.668222  27624.732304
       Spain      38.649135   63352.833746  64181.321963

### **Apply ve Lambda Fonksiyonları**

In [ ]:
df.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15634602  Hargrave          619     Spain  Female   42       2   
1    15647311      Hill          608     Spain  Female   41       1   
3    15701354      Boni          699    France  Female   39       1   
4    15737888  Mitchell          850     Spain  Female   43       2   
5    15574012       Chu          645     Spain    Male   44       8   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   
5  113755.78              2          1               0        149756.71   

   Exited  
0       1  
1       0  
3       0  
4       0  
5       1

In [ ]:
df["Age2"]=df["Age"]*2

In [ ]:
df.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
0    15634602  Hargrave          619     Spain  Female   42       2   
1    15647311      Hill          608     Spain  Female   41       1   
3    15701354      Boni          699    France  Female   39       1   
4    15737888  Mitchell          850     Spain  Female   43       2   
5    15574012       Chu          645     Spain    Male   44       8   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   
5  113755.78              2          1               0        149756.71   

   Exited  Age2  
0       1    84  
1       0    82  
3       0    78  
4       0    86  
5       1    88

In [ ]:
df.loc[:, ["Age","Age2"]].apply(lambda x: (x - x.mean()) / x.std()).head()

Age      Age2
0  0.293519  0.293519
1  0.198174  0.198174
3  0.007485  0.007485
4  0.388863  0.388863
5  0.484208  0.484208

In [ ]:
def standart_scaler(col_name):
  return (col_name - col_name.mean()) / col_name.std()

df.loc[:, ["Age","Age2"]].apply(standart_scaler).head()

Age      Age2
0  0.293519  0.293519
1  0.198174  0.198174
3  0.007485  0.007485
4  0.388863  0.388863
5  0.484208  0.484208

### **Birleştirme işlemleri concat(), merge()**

In [ ]:
df1=df.iloc[:,:6]
df1.head()

CustomerId   Surname  CreditScore Geography  Gender  Age
0    15634602  Hargrave          619     Spain  Female   42
1    15647311      Hill          608     Spain  Female   41
3    15701354      Boni          699    France  Female   39
4    15737888  Mitchell          850     Spain  Female   43
5    15574012       Chu          645     Spain    Male   44

In [ ]:
df2=df.iloc[:,6:]
df2.head()

Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   

   EstimatedSalary  Exited  Age2  
0        101348.88       1    84  
1        112542.58       0    82  
3         93826.63       0    78  
4         79084.10       0    86  
5        149756.71       1    88

In [ ]:
df2["CustomerId"]=df["CustomerId"]

In [ ]:
pd.concat([df1,df2])

CustomerId   Surname  CreditScore Geography  Gender   Age  Tenure  \
0       15634602  Hargrave        619.0     Spain  Female  42.0     NaN   
1       15647311      Hill        608.0     Spain  Female  41.0     NaN   
3       15701354      Boni        699.0    France  Female  39.0     NaN   
4       15737888  Mitchell        850.0     Spain  Female  43.0     NaN   
5       15574012       Chu        645.0     Spain    Male  44.0     NaN   
...          ...       ...          ...       ...     ...   ...     ...   
9995    15606229       NaN          NaN       NaN     NaN   NaN     5.0   
9996    15569892       NaN          NaN       NaN     NaN   NaN    10.0   
9997    15584532       NaN          NaN       NaN     NaN   NaN     7.0   
9998    15682355       NaN          NaN       NaN     NaN   NaN     3.0   
9999    15628319       NaN          NaN       NaN     NaN   NaN     4.0   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0           NaN            NaN        NaN             NaN              NaN   
1           NaN            NaN        NaN             NaN              NaN   
3           NaN            NaN        NaN             NaN              NaN   
4           NaN            NaN        NaN             NaN              NaN   
5           NaN            NaN        NaN             NaN              NaN   
...         ...            ...        ...             ...              ...   
9995       0.00            2.0        1.0             0.0         96270.64   
9996   57369.61            1.0        1.0             1.0        101699.77   
9997       0.00            1.0        0.0             1.0         42085.58   
9998   75075.31            2.0        1.0             0.0         92888.52   
9999  130142.79            1.0        1.0             0.0         38190.78   

      Exited  Age2  
0        NaN   NaN  
1        NaN   NaN  
3        NaN   NaN  
4        NaN   NaN  
5        NaN   NaN  
...      ...   ...  
9995     0.0  78.0  
9996     0.0  70.0  
9997     1.0  72.0  
9998     1.0  84.0  
9999     0.0  56.0  

[19998 rows x 14 columns]

In [ ]:
pd.merge(df1,df2, on="CustomerId")

CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
0       15634602   Hargrave          619     Spain  Female   42       2   
1       15647311       Hill          608     Spain  Female   41       1   
2       15701354       Boni          699    France  Female   39       1   
3       15737888   Mitchell          850     Spain  Female   43       2   
4       15574012        Chu          645     Spain    Male   44       8   
...          ...        ...          ...       ...     ...  ...     ...   
9994    15606229   Obijiaku          771    France    Male   39       5   
9995    15569892  Johnstone          516    France    Male   35      10   
9996    15584532        Liu          709    France  Female   36       7   
9997    15682355  Sabbatini          772   Germany    Male   42       3   
9998    15628319     Walker          792    France  Female   28       4   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0          0.00              1          1               1        101348.88   
1      83807.86              1          0               1        112542.58   
2          0.00              2          0               0         93826.63   
3     125510.82              1          1               1         79084.10   
4     113755.78              2          1               0        149756.71   
...         ...            ...        ...             ...              ...   
9994       0.00              2          1               0         96270.64   
9995   57369.61              1          1               1        101699.77   
9996       0.00              1          0               1         42085.58   
9997   75075.31              2          1               0         92888.52   
9998  130142.79              1          1               0         38190.78   

      Exited  Age2  
0          1    84  
1          0    82  
2          0    78  
3          0    86  
4          1    88  
...      ...   ...  
9994       0    78  
9995       0    70  
9996       1    72  
9997       1    84  
9998       0    56  

[9999 rows x 14 columns]

In [37]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [38]:
df["exited2"]=df["Exited"]*2

In [39]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  exited2  
0        101348.88       1        2  
1        112542.58       0        0  
2        113931.57       1        2  
3         93826.63       0        0  
4         79084.10       0        0